apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    app: front-end
spec:
  containers:
  - name: mynginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
