apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-http-cm
  namespace: staging
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  _;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.html;
        }
        location /test {
          return 402;
        }
        location /success {
        return 200;
        }
      }
    }