apiVersion: v1
kind: Pod
metadata:
 name: kubectl-create-vs-apply-demo
 labels:
  app: front-end
  rel: dev
  environment: local
spec:
 containers:
 - name: httpd
   image: docker.io/httpd
   imagePullPolicy: IfNotPresent
   command:
   - 'bash'
   - '-c'
   - 'echo "hello world example!!!'
   - 'sleep "1000"'
   ports:
   - containerPort: 80