apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-np
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    name: nginx-deployment